apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-selenoid.fullname" . }}
  labels:
    {{- include "test-selenoid.labels" . | nindent 4 }}
data:
  browsers.json: |
    {
    	"chrome": {
    		"default": "latest",
    		"versions": {
    			"latest": {
    				"image": "selenoid/chrome",
    				"port": "4444",
    				"tmpfs": {"/tmp":"size=512m"}
    			}
    		}
    	},
    	"firefox": {
    		"default": "latest",
    		"versions": {
    			"latest": {
    				"image": "selenoid/firefox",
    				"port": "4444",
    				"path": "/wd/hub",
    				"tmpfs": {"/tmp":"size=512m"}
    			}
    		}
    	}
    }
  selenoid: |-
    #!/usr/bin/sh
    set -e
    for i in `seq 0 100`
      do wget 127.0.0.1:2375/version && break || echo waiting && sleep 5 
    done
    # -- This is supposed to get the docker API version
    sed -E 's/.*"ApiVersion":"?([^,"]*)"?.*/\1/' version
    wget --header "Content-Type: application/json" \
      -O - --post-data="-" \
    	127.0.0.1:2375/v1.41/images/create?fromImage=selenoid/chrome:latest
    /usr/bin/selenoid -listen :4444 -conf /etc/selenoid/browsers.json
